# Generated by Django 4.1.4 on 2022-12-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('present_address', models.CharField(max_length=127)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('reg_no', models.CharField(max_length=127, unique=True)),
            ],
        ),
    ]
